language: go

go:
  - 1.11
  - 1.12
  - 1.13
  - 1.14
  - 1.15
  - tip

before_install:
  - cd $GOPATH/src/github.com/fcjr/go-rpi-rgb-led-matrix/lib/rpi-rgb-led-matrix/
  - git submodule update --init
  - make 
  - cd $GOPATH/src/github.com/fcjr/go-rpi-rgb-led-matrix/
  - go get -t -v ./...
  - go install -v ./...
